// A display-only SI unit label for a variable's meaning — used purely to
// annotate a computed answer ("v ≈ 6.32 m/s") the way a person would say it
// out loud. This never drives unit conversion: every calculator in this app
// (this smart-query path included) treats numbers as already being in
// consistent SI units, the same assumption FormulaCalculator has always
// made. A meaning with no entry here just renders without a unit suffix
// rather than guessing.
const UNIT_BY_MEANING: Record<string, string> = {
  mass: 'kg',
  velocity: 'm/s',
  speed: 'm/s',
  'wave speed': 'm/s',
  'speed of light': 'm/s',
  acceleration: 'm/s²',
  'angular acceleration': 'rad/s²',
  'gravitational acceleration': 'm/s²',
  'net force': 'N',
  'applied force': 'N',
  'friction force': 'N',
  'normal force': 'N',
  'centripetal force': 'N',
  'gravitational force': 'N',
  'electrostatic force': 'N',
  'buoyant force': 'N',
  'restoring force exerted by the spring': 'N',
  'kinetic energy': 'J',
  'gravitational potential energy': 'J',
  'elastic potential energy stored in the spring': 'J',
  'photon energy': 'J',
  'work done': 'J',
  energy: 'J',
  'change in gibbs free energy': 'J',
  'change in enthalpy': 'J',
  'change in entropy': 'J/K',
  power: 'W',
  torque: 'N·m',
  momentum: 'kg·m/s',
  'impulse (also equals δp, the change in momentum)': 'N·s',
  displacement: 'm',
  'displacement from equilibrium': 'm',
  height: 'm',
  length: 'm',
  radius: 'm',
  'radius of the circular path': 'm',
  'radius of base': 'm',
  'distance between centers': 'm',
  'distance between charges': 'm',
  'distance between the two points': 'm',
  wavelength: 'm',
  'pendulum length': 'm',
  'lever arm (distance from pivot)': 'm',
  time: 's',
  'time interval': 's',
  'elapsed time': 's',
  'period of oscillation': 's',
  'half-life': 's',
  frequency: 'Hz',
  'sampling frequency': 'Hz',
  'highest frequency in the signal': 'Hz',
  voltage: 'V',
  current: 'A',
  resistance: 'Ω',
  'electric charges': 'C',
  'spring constant': 'N/m',
  density: 'kg/m³',
  'fluid density': 'kg/m³',
  pressure: 'Pa',
  'total pressure': 'Pa',
  'partial pressure of gas i': 'Pa',
  volume: 'm³',
  'displaced fluid volume': 'm³',
  'moles of gas': 'mol',
  'molar concentration': 'mol/L',
  'hydrogen ion concentration': 'mol/L',
  'temperature (k)': 'K',
};

export function unitForMeaning(meaning: string): string | null {
  return UNIT_BY_MEANING[meaning.trim().toLowerCase()] ?? null;
}
